sudo: false
language: python
cache: pip
python:
- 3.4
- 3.5
- 3.6
install: pip install tox-travis codecov
# positional args ({posargs}) to pass into tox.ini
script: tox -- --cov
after_success: codecov
